sudo: required
services:
    - docker

before_install:
    - docker build -t eze09/robofriends -f Dockerfile.dev .
script:
    - docker run -e CI=true eze09/robofriends npm run test
deploy:
    provider: elasticbeanstalk
    access_key_id:
        secure: ACCESS_KEY_ID
    secret_access_key:
        secure: SECRET_ACCESS_KEY
    region: "us-east-1"
    app: "robofriends"
    env: "Robofriends-env"
    bucket_name: "elasticbeanstalk-us-east-1-127772487405"
    on:
        branch:master